DELETE FROM BVR.CONTROLE_MENSAGEM WHERE COD_MENSAGEM in(select COD_MENSAGEM from BVR.MENSAGEM where COD_LINK_PGTO= $codLink$)
DELETE FROM BVR.MENSAGEM_DIRECIONADA WHERE COD_MENSAGEM in(select COD_MENSAGEM from BVR.MENSAGEM where COD_LINK_PGTO= $codLink$)
DELETE FROM BVR.MENSAGEM WHERE COD_LINK_PGTO = $codLink$