DELETE FROM BAG.OFERTA_IMAGEM  WHERE COD_OFERTA in (SELECT COD_OFERTA FROM BAG.OFERTA WHERE EC_CPF_CNPJ = '$cnpjCpf$')
DELETE FROM BAG.HISTORICO_STATUS_OFERTA WHERE COD_OFERTA in (SELECT COD_OFERTA FROM BAG.OFERTA WHERE EC_CPF_CNPJ = '$cnpjCpf$')
DELETE FROM BAG.OFERTA WHERE COD_OFERTA in (SELECT COD_OFERTA FROM BAG.OFERTA WHERE EC_CPF_CNPJ = '$cnpjCpf$')